language: rust
rust:
  - stable

sudo: required

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

env:
  - PKG_CONFIG_PATH="$PKG_CONFIG_PATH:/usr/local/lib/pkgconfig"

install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      wget https://github.com/jedisct1/libsodium/releases/download/1.0.16/libsodium-1.0.16.tar.gz &&
      tar xf libsodium-1.0.16.tar.gz && cd libsodium-1.0.16 &&
      ./configure --prefix=/usr/local/ && make check && sudo make install;
    fi
  - if [ $TRAVIS_OS_NAME == "osx" ]; then
      brew update && brew install libsodium;
    fi

script:
  - cargo test --verbose
  - cargo test --verbose --release